- name: "Working on {{ component }} component"  # Ensure consistent indentation
  hosts: localhost  # Use "hosts" instead of "host"
  become: yes
  roles:
    - "{{ component }}"  # Indent "roles" under "become"
