

---
- name: MongoDB Debugger
  hosts: mongodb  # Replace 'your_target_host' with the actual host or group name
  become: yes
  tasks:
    - name: Print a message
      ansible.builtin.debug:
        msg: "Task started!"
    - name: Move mongo.repo file
      ansible.builtin.copy:
        src: mongo.repo
        dest: /etc/yum.repos.d/mongo.repo

